# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e69b9561910e65a8b4b17b897e81880d620e9358f2796ae87158ee10395f16487a009c451a72e499eceb94c329b193cb3e532b96e6269e40e496a28dd24420

test:
  secret_key_base: a8d043bc0f4aeb65ff3e2b54928423219ac2f7577e5896168e94e814cfbc9ee54c17f92daa00280a4c49ee591db28591489372cda6b89e70b1020246ff84121f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
